### PR TITLE
Set up ProvenanceDM with the history from volute

### PR DESCRIPTION
**Pull request by olebole**
This Pull Request copies the history from the Volute SVN over to Github. This is restricted to the model itself; ProvTAP and ProvSAP are not included here. I took especially care that the history of each source file is kept, including date and time and committer. The history is rebased on top of the initial `README.md` in the repository.

The original branch also contains [tags for all versions](https://github.com/olebole/ProvenanceDM/releases), which could be attached as well:

| Version | Type |
|---------|---------|
| v0.1_20141008 | Internal draft |
| v0.2_20160428 | Internal draft |
| v1.0_20161121-wd | Working Draft |
| v1.0_20170514-wd | Working Draft |
| v1.0_20170921-wd | Working Draft |
| v1.0_20180530-wd | Working Draft |
| v1.0_20181015-pr | Proposed Recommendation |
| v1.0_20190614-wd | Working Draft |
| v1.0_20190719-pr | Proposed Recommendation |
| v1.0_20191125-pr | Proposed Recommendation |
| v1.0_20191214-pr | Proposed Recommendation |
| ***v1.0*** | ***Final Release*** |

According to our Github policy, I removed the generated PDFs; they are going to be re-added to the tags once the tags are created on the official place. I volunteer to do both tagging and adding the PDFs once the PR is merged.

Current and previous working group members are @mservillat, @kristinriebe, @bonnarel, @cboisson, @galkinAIP, @loumir, @mnullmei, Nicolas Renault-Tinacci (no github user name known), @sanguillon, @olebole (listed here to let them know and comment on this PR).

### CODE REVIEW

**Comment by olebole** [comment]
Pinging Provenance working group for this initial PR...

**Review by lmichel — APPROVED** [review]
This PR just includes the file history from Volute. It seams not to impact the current document.

**Comment by mservillat** [comment]
Thanks for this import. It would be nice to include a README with the changes as listed in the document, as it is a more relevant provenance than the volute commits.

**Comment by olebole** [comment]
@mservillat I think that the list of changes should go either into a `CHANGES.md` file (which is the standard here). The longer-term problem in either case is however that this basically duplicates what is in `doc/changes.tex`, and the chance that they run out of sync is not negligible. If you want to go this way: just create a PR ;-)

The other way would be to put them into the descriptions of the document revisions. I would volunteer to do this together with putting the tags here, if I would get (temporary) write access to this repository -- this is unfortunately not possible to do as a Pull Request.

And, finally, I would encourage everyone to write useful commit messages in future ;-)

**Comment by mservillat** [comment]
the commits are useful, they just have a different granularity compared to the sequence of released WD and PR. Indeed the changes are already in the tex document, so I proposed just a basic readme.

**Comment by olebole** [comment]
"Minor changes" is just not a good commit message. You also find completely empty commit messaged in the list, duplicated messages for adjacent commits etc.

There is a recommendation on how good commit messages should look like, see f.e [this blog post](https://chris.beams.io/posts/git-commit/).

**Pull request merged**
